### ISSUE TITLE
Episodes watched bulk 

### ISSUE THREAD

**Issue by splendid25** [skylex/xbmc-betaseries#10]
Bonjour,

Je rencontre un bug, sur la méthode POST episodes/watched.

J'ai installé l'addon Kodi, et quand je regarde un épisode, ça me marque tous les précédents comme déjà vus, quelle que soit la valeur du paramètre bulk.

**Comment by skylex** [comment]
Bonjour,
Je vais voir si je peux mettre à jour le plugin pour supporter les nouvelles fonctionnalités de l'API, ce n'était pas géré avant.
Merci
