### ISSUE TITLE
Addicted always finds no subtitles when using xbmctorrent

### ISSUE THREAD

**Issue by n37** [skylex/xbmc-betaseries#2]
I am trying to download subtitles from addicted while watching something by the help of the xbmctorrent addon. I always get a message that no subtitles were found. I know that there are subtitles on addicted for the episode and I tied a number of different episodes. So there is something wrong with the way your script does the search. Also if I first download the episode locally and watch it the usual way (not by xbmctorrent) and try to find subtitles then everything is OK. Unfortunately when watching the same episode with xbmctorrent this is impossible. This happens even if I use manual search and input the title of the episode myself. Otoh, the opensubtitles script works fine with xbmctorrent.

**Comment by skylex** [comment]
no it just can't work that way, sorry
