### ISSUE TITLE
Addic7ed subtitle improvement

### ISSUE THREAD

**Issue by dahouet** [skylex/xbmc-betaseries#7]
Hello

Thanks for the great work.
On the website Addic7ed, subtitles are available to download even if the subtitle is not 100% complete.

It will be very nice to prevent or specify when a subtitle has not reach 100% completion.
I'm very familiar with python to submit a patch, but if someone is up for it.

Thanks

**Comment by skylex** [comment]
Hello,
That's simple, the subtitles with no star (lowest note) are the ones that are not complete.
Regards,

**Comment by skylex** [comment]
I added a new option to hide them anyway ;)
